import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";

const getFigtree = Figtree({
  variable: "--font-fig",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Diagnosis Aid",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${getFigtree.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
